services:
  rpg:
    image: ${DOCKER_REGISTRY-}zendered/rpg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - sqlserverdb
  sqlserverdb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "MSSQL_SA_PASSWORD=Passw#2022"
      - "ACCEPT_EULA=Y"
    volumes:
      - "./Data/Volumes:/var/opt/mssql/data"
    ports:
      - "1433:1433"